LaKultural/LaKultural/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('usuarios/', include ('usuarios.urls')),
    path('tienda/', include ('tienda.urls')),
    path('servicios/', include ('servicios.urls')),
    path('musica/', include ('musica.urls')),
    path('eventos/', include ('eventos.urls')),
    path('booking/', include ('booking.urls')),
    path('biografia/', include ('biografia.urls')),
    path('carrito/', include ('carrito.urls')),
    path('', include ('core.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LaKultural/booking/urls.py
from django.urls import path
from . import views

app_name = 'booking' 

urlpatterns = [
    path('', views.booking, name='booking'),
    path('artista/<int:artista_id>', views.artista, name='artista'),
]

LaKultural/core/urls.py
from django.urls import path
from . import views

app_name = 'core' 

urlpatterns = [
    path('', views.home, name='home'),
    path('buscar/', views.buscar, name='buscar'),
]

LaKultural/eventos/urls.py
from django.urls import path
from . import views

app_name = 'eventos' 

urlpatterns = [
    path('', views.eventos, name='eventos'),
    path('eventos/<int:evento_id>', views.evento, name='evento'),
]

LaKultural/musica/urls.py
from django.urls import path
from . import views

app_name = 'musica' 

urlpatterns = [
    path('', views.musica, name='musica'),
    path('musica/cancion_detalle/<int:id>/', views.cancion_detalle, name='cancion_detalle')
]

LaKultural/tienda/urls.py
from django.urls import path
from . import views

app_name = 'tienda' 

urlpatterns = [
    path('', views.tienda, name='tienda'),
    path('tienda/<int:producto_id>', views.producto, name='producto'),
]

LaKultural/core/models.py
from django.db import models

# Create your models here.

LaKultural/core/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.db.models import Q
from eventos.models import Evento
from booking.models import Artista
from tienda.models import Producto


def home(request):
    contexto = {'mensaje': "Hola, mundo. Este es mi contexto."}
    return render(request, 'core/home.html', contexto)



def buscar(request):
    if request.is_ajax():
        query = request.GET.get('term', '')  # 'term' será lo que el usuario está escribiendo
        eventos = Evento.objects.filter(nombre__icontains=query)
        artistas = Artista.objects.filter(nombre__icontains=query)
        productos = Producto.objects.filter(nombre__icontains=query)
        results = []
        for evento in eventos:
            results.append(evento.nombre)
        for artista in artistas:
            results.append(artista.nombre)
        for producto in productos:
            results.append(producto.nombre)
        data = {
            'list': results
        }
        return JsonResponse(data)
    else:
        return JsonResponse({"error": "Error: no se realizó una solicitud AJAX"}, status=400)

LaKultural/core/templates/core/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!-- Usamos 'vh-100' para hacer que el contenedor tenga al menos el alto de la pantalla -->
<!-- 'd-flex' hace que el contenedor use Flexbox -->
<!-- 'justify-content-center' centra los elementos en el eje horizontal -->
<!-- 'align-items-center' centra los elementos en el eje vertical -->
<div class="container d-flex vh-100 justify-content-center align-items-center">
  <div id="floating-vinyls">
    <img src="{% static 'assets/img/vinyl.png' %}" alt="Vinyl" class="floating-vinyl"/>
    <img src="{% static 'assets/img/vinyl.png' %}" alt="Vinyl" class="floating-vinyl"/>
    <img src="{% static 'assets/img/vinyl.png' %}" alt="Vinyl" class="floating-vinyl"/>
  </div>
  <div class="d-block d-md-none">
    <div class="row">
      <!-- Aplicamos una clase personalizada para efectos de hover -->
      <div class="col-6 thumbnail-hover">
        <a href="{% url 'tienda:tienda' %}">
          <img src="{% static 'assets/img/links/tienda.png' %}" alt="Tienda" style="--animation-order:1;" class="img-fluid rounded-3 mb-2 thumbnail"/>
          <div class="thumbnail-text">Tienda</div>
        </a>
      </div>
      <div class="col-6 thumbnail-hover">
        <a href="{% url 'musica:musica' %}">
          <img src="{% static 'assets/img/links/musica.png' %}" alt="Música" style="--animation-order:2;" class="img-fluid rounded-3 mb-2 thumbnail"/>
          <div class="thumbnail-text">Música</div>
        </a>
      </div>
      <div class="col-6 thumbnail-hover">
        <a href="{% url 'eventos:eventos' %}">
          <img src="{% static 'assets/img/links/eventos.png' %}" alt="Eventos" style="--animation-order:3;" class="img-fluid rounded-3 thumbnail"/>
          <div class="thumbnail-text">Eventos</div>
        </a>
      </div>
      <div class="col-6 thumbnail-hover">
        <a href="{% url 'booking:booking' %}">
          <img src="{% static 'assets/img/links/booking.png' %}" alt="Booking" style="--animation-order:4;" class="img-fluid rounded-3 thumbnail"/>
          <div class="thumbnail-text">Booking</div>
        </a>
      </div>
    </div>
  </div>

  <!-- Contenido para dispositivos no móviles: mantener el contenido existente -->
  <div class="d-none d-md-block">
    <main class="px-3 main-cover mx-auto my-auto">
        <h1>la Kultural</h1>
        <p class="lead">Since 2016.</p>
        <p class="lead">
          <a href="#" class="btn btn-lg btn-light fw-bold border-white bg-white">Learn more</a>
        </p>
    </main>
  </div>
</div>

{% endblock %}