LaKultural/LaKultural/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('usuarios/', include ('usuarios.urls')),
    path('tienda/', include ('tienda.urls')),
    path('servicios/', include ('servicios.urls')),
    path('musica/', include ('musica.urls')),
    path('eventos/', include ('eventos.urls')),
    path('booking/', include ('booking.urls')),
    path('biografia/', include ('biografia.urls')),
    path('carrito/', include ('carrito.urls')),
    path('', include ('core.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LaKultural/carrito/urls.py
from django.urls import path
from . import views

app_name = 'carrito' 

urlpatterns = [
    path('', views.carrito, name='carrito'),
    path('agregar/<int:producto_id>/', views.agregar_producto, name='agregar_producto'),
    path('quitar/<int:item_id>/', views.quitar_producto, name='quitar_producto'),    
    path('checkout/', views.checkout, name='checkout'),    
    path('update/<int:item_id>/<int:product_id>/<int:quantity>/', views.update_item_quantity, name='update_item_quantity'),
]

LaKultural/core/urls.py
from django.urls import path
from . import views

app_name = 'core' 

urlpatterns = [
    path('', views.home, name='home'),
    path('buscar/', views.buscar, name='buscar'),
]

LaKultural/tienda/urls.py
from django.urls import path
from . import views

app_name = 'tienda' 

urlpatterns = [
    path('', views.tienda, name='tienda'),
    path('tienda/<int:producto_id>', views.producto, name='producto'),
]

LaKultural/carrito/models.py
from django.db import models
from usuarios.models import Usuario
from tienda.models import Producto

class Carrito(models.Model):
    usuario = models.OneToOneField(Usuario, on_delete=models.CASCADE, related_name="carrito")
    creado_en = models.DateTimeField(auto_now_add=True)

    def total_carrito(self):
        return sum(item.subtotal() for item in self.items.all())
    
    def __str__(self):
        return f"Carrito de {self.usuario.username}"

class ItemCarrito(models.Model):
    carrito = models.ForeignKey(Carrito, related_name='items', on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.IntegerField(default=0)

    def subtotal(self):
        return self.cantidad * self.producto.precio

    def __str__(self):
        return f"{self.cantidad} de {self.producto.nombre}"

LaKultural/carrito/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.http import JsonResponse
from tienda.models import Producto
from .models import Carrito, ItemCarrito

def carrito(request):
    #selecciona solo los 2 primeros productos si existen:
    productos = Producto.objects.all()
    productos = productos[:2]
    try:
        carrito = Carrito.objects.get(usuario=request.user)
        items = carrito.items.all()
        total_articulos = sum(item.cantidad for item in items)
    except Carrito.DoesNotExist:
        items = []
        total_articulos = 0
    return render(request, 'carrito/carrito.html', {'carrito': carrito,
                                                    'items': items,
                                                    'productos': productos,
                                                    'total_articulos': total_articulos})

def agregar_producto(request, producto_id):
    producto = get_object_or_404(Producto, id=producto_id)
    carrito, created = Carrito.objects.get_or_create(usuario=request.user)
    item, created = ItemCarrito.objects.get_or_create(carrito=carrito, producto=producto)
    item.cantidad += 1
    item.save()
    return redirect('carrito:carrito')

def quitar_producto(request, item_id):
    item = get_object_or_404(ItemCarrito, id=item_id)
    if item.cantidad > 1:
        item.cantidad -= 1
        item.save()
    else:
        item.delete()
    return redirect('carrito:carrito')

def checkout(request):
    carrito = Carrito.objects.get(usuario=request.user)
    items = carrito.items.all()
    total = carrito.total_carrito()
    return render(request, 'carrito/checkout.html', {'carrito': carrito,
                                                    'items': items,
                                                    'total': total})



def update_item_quantity(request, item_id, product_id, quantity):
    item = get_object_or_404(ItemCarrito, id=item_id, producto_id=product_id)
    item.cantidad = int(quantity)
    item.save()

    carrito = item.carrito
    total_carrito = sum(item.subtotal() for item in carrito.items.all())
    total_items = sum(item.cantidad for item in carrito.items.all())  # Total de artículos

    return JsonResponse({
        'subtotal': item.subtotal(),
        'total_carrito': total_carrito,
        'total_items': total_items  # Devuelve el total de artículos en el carrito
    })

LaKultural/carrito/templates/carrito/carrito.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!-- Masthead-->
<header class="masthead">
    <div class="text-center">
        <h1 class="section-heading text-uppercase">CARRITO</h1>
    </div>
</header>
<!--def carrito(request):
    carrito = get_carrito_or_create(request)
    contexto = {'carrito': carrito}
    return render(request, 'carrito/carrito.html', contexto)

def add_producto(request, producto_id):
    carrito = get_carrito_or_create(request)
    producto = get_object_or_404(Producto, id=producto_id)

    carrito.productos.add(producto)
    return render(request, 'carrito/carrito.html', {'carrito': carrito})

def remove_producto(request, producto_id):
    carrito = get_carrito_or_create(request)
    producto = Producto.objects.get(id=producto_id)
    
    carrito.productos.remove(producto)
    return render(request, 'carrito/carrito.html', {'carrito': carrito})
'''
-->

<div class="container">
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-md-9">
            <div class="ibox">
                <div class="ibox-title">
                    <span class="pull-right">(<strong>5</strong>) items</span>
                    <h5>Items in your cart</h5>
                </div>
                {% for item in items %}
                <div class="ibox-content">
                    <div class="table-responsive">
                        <table class="table shoping-cart-table">
                            <tbody>
                            <tr>
                                <td width="90">
                                    <div class="cart-product-imitation">
                                    </div>
                                </td>
                                <td class="desc">
                                    <h3>
                                    <a href="#" class="text-navy">
                                        {{ item.producto.nombre }}
                                    </a>
                                    </h3>
                                    <p class="small">
                                        {{ item.producto.descripcion }}
                                    </p>
                                    <dl class="small m-b-none">
                                        <dt>Categoría</dt>
                                        <dd>{{ item.producto.categoria.nombre }}</dd>
                                    </dl>
                                    <div class="m-t-sm">
                                        <a href="{% url 'carrito:quitar_producto' item.id %}" class="text-muted"><i class="fa fa-trash"></i> Remove item</a>
                                    </div>
                                </td>
                                <td>
                                    {% if item.producto.descuento_activo %}
                                    {{ item.producto.precio_descuento }} €
                                    <s class="small text-muted">{{ item.producto.precio }} €</s>
                                    {% else %}
                                    {{ item.producto.precio }} €
                                    {% endif %}
                                </td>
                                <td width="65">
                                    <input type="number" class="form-control w-auto quantity-input" data-product-id="{{ item.producto.id }}" value="{{ item.cantidad }}" name="cantidad" min="1" max="100" data-item-id="{{ item.id }}">
                                </td>
                                <td>
                                    <h4 class="subtotal" data-item-id="{{ item.id }}">
                                        {{ item.subtotal }} €
                                    </h4>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
                {% endfor %}
                <div class="ibox-content">
                    <a href="{% url 'tienda:tienda'  %}" class="btn btn-white"><i class="fa fa-arrow-left"></i> Seguir comprando</a>
                    <a href="{% url 'carrito:checkout' %}" class="btn btn-primary pull-right"><i class="fa fa-shopping-cart"></i> Checkout</a>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="ibox">
                <div class="ibox-title">
                    <h5>Resumen del pedido</h5>
                </div>
                <div class="ibox-content">
                    <span>
                        Total
                    </span>
                    <h2 class="font-bold total-carrito">
                        {{ carrito.total_carrito }} 
                    </h2>
                    <hr>
                    <span class="text-muted small">
                        *Los envíos superiores a 40€ son gratuitos
                    </span>
                    <div class="m-t-sm">
                        <div class="btn-group">
                        <a href="{% url 'carrito:checkout' %}" class="btn btn-primary btn-sm"><i class="fa fa-shopping-cart"></i> Continuar</a>
                        <a href="{% url 'tienda:tienda'  %}" class="btn btn-white btn-sm"> Cancelar</a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="ibox">
                <div class="ibox-title">
                    <h5>Soporte</h5>
                </div>
                <div class="ibox-content text-center">
                    <h3><i class="fa fa-phone"></i> 608 02 03 04</h3>
                    <span class="small">
                        En caso de tener algun problema durante la compra no dude contactar con nosotros.
                    </span>
                </div>
            </div>

            <div class="ibox">
                <div class="ibox-content">
                    <p class="font-bold">
                    Otros productos que te pueden interesar
                    </p>
                    <hr>
                    {% for producto in productos %}
                    <div>
                        <a href="#" class="product-name"> {{ producto.nombre }}</a>
                        <div class="small m-t-xs">
                            {{ producto.descripcion}}
                        </div>
                        <div class="m-t text-righ">

                            <a href="#" class="btn btn-xs btn-outline btn-primary">Info <i class="fa fa-long-arrow-right"></i> </a>
                        </div>
                    </div>
                    {% endfor %}
                    <hr>
                </div>
            </div>
        </div>
    </div>
</div>
</div>


{% endblock %}

LaKultural/carrito/templates/carrito/carrito_old.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!-- Masthead-->
<header class="masthead">
    <div class="text-center">
        <h1 class="section-heading text-uppercase">CARRITO</h1>
    </div>
</header>

<div class="container">
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-md-9">
            <div class="ibox">
                <div class="ibox-title">
                    <span class="pull-right total-items">(<strong>{{ total_articulos  }}</strong>) artículos</span>
                    <h5>Artículos en el carrito</h5>
                </div>
                
            <!-- CARRITO LIST -->
            <div class="list-group list-group-flush">
                {% for item in items %}
                <!-- List items dynamically generated. -->
                <div class="row carrito-list list-group-item align-items-center text-start">

                    <!-- NOM PRODUCTE -->
                    <div class="col-3 col-lg-1">
                    <img src="{% static 'assets/img/events/event1.png' %}" class="img-fluid rounded-2" alt="Carrito">
                    </div>
                
                    <!-- NOM I CATEGORIA PRODUCTE -->
                    <div class="col-7 col-lg-3">
                        <div class="fw-bold">{{ item.producto.nombre }}</div>
                        <div>{{ item.producto.categoria.nombre }}</div>
                    </div>
                
                    <!-- PREU PRODUCTE -->
                    <div class="col-lg-2 d-none d-lg-block">
                        {% if item.producto.descuento_activo %}
                        {{ item.producto.precio_descuento }} €
                        <s class="small text-muted">{{ item.producto.precio }} €</s>
                        {% else %}
                        {{ item.producto.precio }} €
                        {% endif %}
                    </div>
                
                    <!-- QUANTITAT -->
                    <div class="col-lg-2 d-none d-lg-block">
                        <input type="number" class="form-control w-auto quantity-input" data-product-id="{{ item.producto.id }}" value="{{ item.cantidad }}" name="cantidad" min="1" max="100" data-item-id="{{ item.id }}">
                    </div>
                
                    <!-- SUBTOTAL PRODUCTE -->
                    <div class="col-lg-2 d-none d-lg-block">
                        <h4 class="subtotal" data-item-id="{{ item.id }}">
                            {{ item.subtotal }} €
                        </h4>
                    </div>
                    
                    <!-- Action Buttons for non-mobile view -->
                    <div class="col-lg-2 d-none d-lg-flex justify-content-end">
                        <a href="{% url 'carrito:quitar_producto' item.id %}" class="text-muted"><i class="fa fa-trash"></i></a>
                    </div>
            
            
                </div>
                {% endfor %}
                </div>

                <div class="ibox-content">
                    <a href="{% url 'tienda:tienda'  %}" class="btn btn-white"><i class="fa fa-arrow-left"></i> Seguir comprando</a>
                    <a href="{% url 'carrito:checkout' %}" class="btn btn-primary pull-right"><i class="fa fa-shopping-cart"></i> Checkout</a>
                </div>
            </div>
        </div>
        <div class="col-md-3 tarjeta-checkout">
            <div class="ibox">
                <div class="ibox-title">
                    <h5>Resumen del pedido</h5>
                </div>
                <div class="ibox-content">
                    <span>
                        Total
                    </span>
                    <h2 class="font-bold total-carrito">
                        {{ carrito.total_carrito }} €
                    </h2>
                    <hr>
                    <span class="text-muted small">
                        *Los envíos superiores a 40€ son gratuitos
                    </span>
                    <div class="m-t-sm">
                        <div class="btn-group">
                        <a href="{% url 'carrito:checkout' %}" class="btn btn-primary btn-sm"><i class="fa fa-shopping-cart"></i> Continuar</a>
                        <a href="{% url 'tienda:tienda'  %}" class="btn btn-white btn-sm"> Cancelar</a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="ibox">
                <div class="ibox-title">
                    <h5>Soporte</h5>
                </div>
                <div class="ibox-content text-center">
                    <h3><i class="fa fa-phone"></i> 608 02 03 04</h3>
                    <span class="small">
                        En caso de tener algún problema durante la compra no dude contactar con nosotros mediante este <a href="#">enlace</a>.   
                    </span>
                </div>
            </div>

            <div class="ibox">
                <div class="ibox-content">
                    <p class="font-bold">
                    Otros productos que te pueden interesar
                    </p>
                    <hr>
                    {% for producto in productos %}
                    <div>
                        <a href="#" class="product-name"> {{ producto.nombre }}</a>
                        <div class="small m-t-xs">
                            {{ producto.descripcion}}
                        </div>
                        <div class="m-t text-righ">

                            <a href="#" class="btn btn-xs btn-outline btn-primary">Info <i class="fa fa-long-arrow-right"></i> </a>
                        </div>
                    </div>
                    {% endfor %}
                    <hr>
                </div>
            </div>
        </div>
    </div>
</div>
</div>


{% endblock %}

LaKultural/carrito/templates/carrito/checkout.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

Checkout

{% endblock %}