LaKultural/LaKultural/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('usuarios/', include ('usuarios.urls')),
    path('tienda/', include ('tienda.urls')),
    path('servicios/', include ('servicios.urls')),
    path('musica/', include ('musica.urls')),
    path('eventos/', include ('eventos.urls')),
    path('booking/', include ('booking.urls')),
    path('biografia/', include ('biografia.urls')),
    path('carrito/', include ('carrito.urls')),
    path('', include ('core.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LaKultural/booking/urls.py
from django.urls import path
from . import views

app_name = 'booking' 

urlpatterns = [
    path('', views.booking, name='booking'),
    path('artista/<int:artista_id>', views.artista, name='artista'),
]

LaKultural/carrito/urls.py
from django.urls import path
from . import views

app_name = 'carrito' 

urlpatterns = [
    path('', views.carrito, name='carrito'),
    path('agregar/<int:producto_id>/', views.agregar_producto, name='agregar_producto'),
    path('quitar/<int:item_id>/', views.quitar_producto, name='quitar_producto'),    
    path('checkout/', views.checkout, name='checkout'),    
    path('update/<int:item_id>/<int:product_id>/<int:quantity>/', views.update_item_quantity, name='update_item_quantity'),
]

LaKultural/core/urls.py
from django.urls import path
from . import views

app_name = 'core' 

urlpatterns = [
    path('', views.home, name='home'),
    path('buscar/', views.buscar, name='buscar'),
]

LaKultural/musica/urls.py
from django.urls import path
from . import views

app_name = 'musica' 

urlpatterns = [
    path('', views.musica, name='musica'),
    path('musica/cancion_detalle/<int:id>/', views.cancion_detalle, name='cancion_detalle')
]

LaKultural/tienda/urls.py
from django.urls import path
from . import views

app_name = 'tienda' 

urlpatterns = [
    path('', views.tienda, name='tienda'),
    path('tienda/<int:producto_id>', views.producto, name='producto'),
]

LaKultural/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" data-bs-theme="auto">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="laKultural, asociación productora de musica y organizadora de eventos musicales">
        <meta name="author" content="" />
        <title>la Kultural</title>

        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />

        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        
        <!-- Inclusión de jQuery -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

       
        <!-- Custom theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>

        <!-- Google fonts -->
        <!--<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" /> -->
        <!--<link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" /> -->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>      
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,900|Open+Sans:400,400i,700,900" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/base.css' %}" rel="stylesheet" />
        <link href="{% static 'css/navbar.css' %}" rel="stylesheet" />
        <link href="{% static 'usuarios/css/login_logout.css' %}" rel="stylesheet" />
        <link href="{% static 'eventos/css/evento.css' %}" rel="stylesheet" />
        <link href="{% static 'musica/css/musica.css' %}" rel="stylesheet" />
        <link href="{% static 'tienda/css/producto.css' %}" rel="stylesheet" />
        <link href="{% static 'carrito/css/carrito.css' %}" rel="stylesheet" />
    </head>

    <body class="d-flex w-100 text-center text-bg-dark p-3 mx-auto flex-column" data-bs-theme="dark">
        
        <!-- Navigation-->
        {% include 'navbar.html' %}

        
        {% block content %}
        {% endblock %}

        {% include 'footer.html' %}
        
    </body>
</html>

LaKultural/templates/clients.html
{% load static %}
<!-- Clients-->
<div class="py-5">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-md-3 col-sm-6 my-3">
                <a href="#!"><img class="img-fluid img-brand d-block mx-auto" src="{% static 'assets/img/logos/microsoft.svg' %}" alt="..." aria-label="Microsoft Logo" /></a>
            </div>
            <div class="col-md-3 col-sm-6 my-3">
                <a href="#!"><img class="img-fluid img-brand d-block mx-auto" src="{% static 'assets/img/logos/google.svg' %}" alt="..." aria-label="Google Logo" /></a>
            </div>
            <div class="col-md-3 col-sm-6 my-3">
                <a href="#!"><img class="img-fluid img-brand d-block mx-auto" src="{% static 'assets/img/logos/facebook.svg' %}" alt="..." aria-label="Facebook Logo" /></a>
            </div>
            <div class="col-md-3 col-sm-6 my-3">
                <a href="#!"><img class="img-fluid img-brand d-block mx-auto" src="{% static 'assets/img/logos/ibm.svg' %}" alt="..." aria-label="IBM Logo" /></a>
            </div>
        </div>
    </div>
</div>

LaKultural/templates/contact.html
{% load static %}

<!-- Contact-->
<section class="page-section" id="contact">
    <div class="container">
        <div class="text-center">
            <h2 class="section-heading text-uppercase">Contact Us</h2>
            <h3 class="section-subheading text-muted">Lorem ipsum dolor sit amet consectetur.</h3>
        </div>
        <!-- * * * * * * * * * * * * * * *-->
        <!-- * * SB Forms Contact Form * *-->
        <!-- * * * * * * * * * * * * * * *-->
        <!-- This form is pre-integrated with SB Forms.-->
        <!-- To make this form functional, sign up at-->
        <!-- https://startbootstrap.com/solution/contact-forms-->
        <!-- to get an API token!-->
        <form id="contactForm" data-sb-form-api-token="API_TOKEN">
            <div class="row align-items-stretch mb-5">
                <div class="col-md-6">
                    <div class="form-group">
                        <!-- Name input-->
                        <input class="form-control" id="name" type="text" placeholder="Your Name *" data-sb-validations="required" />
                        <div class="invalid-feedback" data-sb-feedback="name:required">A name is required.</div>
                    </div>
                    <div class="form-group">
                        <!-- Email address input-->
                        <input class="form-control" id="email" type="email" placeholder="Your Email *" data-sb-validations="required,email" />
                        <div class="invalid-feedback" data-sb-feedback="email:required">An email is required.</div>
                        <div class="invalid-feedback" data-sb-feedback="email:email">Email is not valid.</div>
                    </div>
                    <div class="form-group mb-md-0">
                        <!-- Phone number input-->
                        <input class="form-control" id="phone" type="tel" placeholder="Your Phone *" data-sb-validations="required" />
                        <div class="invalid-feedback" data-sb-feedback="phone:required">A phone number is required.</div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group form-group-textarea mb-md-0">
                        <!-- Message input-->
                        <textarea class="form-control" id="message" placeholder="Your Message *" data-sb-validations="required"></textarea>
                        <div class="invalid-feedback" data-sb-feedback="message:required">A message is required.</div>
                    </div>
                </div>
            </div>
            <!-- Submit success message-->
            <!---->
            <!-- This is what your users will see when the form-->
            <!-- has successfully submitted-->
            <div class="d-none" id="submitSuccessMessage">
                <div class="text-center text-white mb-3">
                    <div class="fw-bolder">Form submission successful!</div>
                    To activate this form, sign up at
                    <br />
                    <a href="https://startbootstrap.com/solution/contact-forms">https://startbootstrap.com/solution/contact-forms</a>
                </div>
            </div>
            <!-- Submit error message-->
            <!---->
            <!-- This is what your users will see when there is-->
            <!-- an error submitting the form-->
            <div class="d-none" id="submitErrorMessage"><div class="text-center text-danger mb-3">Error sending message!</div></div>
            <!-- Submit Button-->
            <div class="text-center"><button class="btn btn-primary btn-xl text-uppercase disabled" id="submitButton" type="submit">Send Message</button></div>
        </form>
    </div>
</section>

LaKultural/templates/faqs.html
{% load static %}
<h2 class="mb-4">FAQS</h2>
<div class="accordion" id="FAQaccordion">

    <div class="accordion-item">
      <h2 class="accordion-header">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
          ¿Necesito comprar entrada?
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse" data-bs-parent="#FAQaccordion">
        <div class="accordion-body">
          <strong></strong> Aunque hay eventos en los que tenemos entradas disponibles en taquilla, siempre es recomendable que la compres anticipada en la web, ya que de esta forma te aseguras que no se agoten. Vigila, ha que hay eventos que no tendrán entrada disponible en taquilla si se vende todo por anticipado.
        </div>
      </div>
    </div>

    <div class="accordion-item">
      <h2 class="accordion-header">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          No recibo la entrada que acabo de comprar
        </button>
      </h2>
      <div id="collapseTwo" class="accordion-collapse collapse" data-bs-parent="#FAQaccordion">
        <div class="accordion-body">
          Al comprar una entrada en nuestra web automáticamente se te envía un correo con el resumen del pedido. Justo debajo de la tabla donde sale el tipo de entrada que has comprado, cantidad y precio, también encontrarás una tabla con las diferentes entradas y un botón «DOWNLOAD» junto a cada una desde donde puedes descargarlas.

          En caso de no haber recibido el correo revisa la carpeta SPAM.

          Si estás seguro de que no has recibido el correo, puedes contactarnos a tickets@midnight.es y solucionaremos el problema con la mayor brevedad posible.

          EN NINGÚN CASO se debe comprar una nueva entrada, ya que entonces no podremos realizar la devolución de la anterior si realmente se ha cobrado. Antes de hacer ninguna operación rogamos que compruebes si el importe se ha cobrado en su cuenta y contactes con nosotros.
        </div>
      </div>
    </div>

    <div class="accordion-item">
      <h2 class="accordion-header">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          ¿Puedo devolver la entrada?
        </button>
      </h2>
      <div id="collapseThree" class="accordion-collapse collapse" data-bs-parent="#FAQaccordion">
        <div class="accordion-body">
          <strong>Lamentablemente no aceptamos devoluciones</strong> por causas ajenas a la organización. En caso de no poder asistir y querer pasar tu entrada a alguien de tu entorno puedes hacerlo sin problema aunque aparezca tu nombre.
          La imposibilidad de acceder al evento por no presentar los documentos pertinentes, tanto de identificación personal como de certificado COVID, NO son motivo para proceder a un reembolso.
        </div>
      </div>
    </div>
  </div>

LaKultural/templates/footer.html
{% load static %}
<!-- Footer-->
<footer class="mt-auto text-white-50">
    <p>Web Design for <a href="https://getbootstrap.com/" class="text-white">la Kultural</a>, by <a href="#" class="text-white">@akosta</a>.</p>
  </footer>

LaKultural/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg fixed-top navbar-scroll px-3" aria-label="Main navigation">
  <div class="container-fluid">   
    <a class="navbar-brand" href="{% url 'core:home' %}">
      <img src="{% static 'assets/img/logos/k_lakultural_lletres_blanc.svg' %}" alt="La Kultural Logo" height="60px" style="max-width: 150px;">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar2" aria-controls="offcanvasNavbar2" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasNavbar2" aria-labelledby="offcanvasNavbar2Label">
      <div class="offcanvas-header">
        <img src="{% static 'assets/img/logos/k_blanca.svg' %}" alt="La Kultural Logo" height="30px" style="max-width: 100px;">
        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">        
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3 text-start">
          <div class="menu-items">
          <li class="nav-item"><a class="nav-link" href="{% url 'tienda:tienda' %}">TIENDA</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'musica:musica' %}">CANCIONES</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'eventos:eventos' %}">EVENTOS</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'booking:booking' %}">BOOKING</a></li>
        </div>
        <div class="control-items">
          <li class="nav-item">
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Buscar" aria-label="Search">
            </form>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item"><a class="nav-link" href="{% url 'carrito:carrito' %}">
            <div class="svg-image">
              <img src="{% static 'assets/img/icons/shopping-bag.svg' %}" alt="Cart Icon" class='icon-menu normal'>
              <img src="{% static 'assets/img/icons/shopping-bag_green.svg' %}" alt="Cart Icon" class='icon-menu hover'>
            </div>
            </a>
          </li>
          {% endif %}

          <li class="nav-item dropdown">
            <a class="nav-link" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <div class="svg-image">
                <img src="{% static 'assets/img/icons/menu_user.svg' %}" alt="User Icon" class='icon-menu normal'>
                <img src="{% static 'assets/img/icons/menu_user_green.svg' %}" alt="User Icon" class='icon-menu hover'>
              </div>
            </a>
            <ul class="dropdown-menu dropdown-menu-end">
              {% if user.is_authenticated %}
                <li><a class="dropdown-item" href="{% url 'usuarios:ajustes' %}">Ajustes</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="{% url 'usuarios:logout' %}">Cerrar Sesión</a></li>
              {% else %}
                <li><a class="dropdown-item" href="{% url 'usuarios:login' %}">Iniciar Sesión</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="{% url 'usuarios:signup' %}">Registrarse</a></li>
              {% endif %}
            </ul>
          </li>
        </div>

        </ul>
      </div>
    </div>
  </div>
</nav>

LaKultural/templates/navbar_old.html
{% load static %}
<nav class="navbar navbar-expand-lg fixed-top navbar-scroll px-3" aria-label="Offcanvas navbar large">
  <div class="container-fluid">   
    <a class="navbar-brand" href="{% url 'core:home' %}">
      <img src="{% static 'assets/img/logos/k_lakultural_lletres_blanc.svg' %}" alt="lakultulogo" height="60px" width="100%">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar2" aria-controls="offcanvasNavbar2" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasNavbar2" aria-labelledby="offcanvasNavbar2Label">
      <div class="offcanvas-header">
        <img src="{% static 'assets/img/logos/k_lakultural_lletres_blanc.svg' %}" alt="lakultulogo" height="30px" width="100%">
        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">        
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3 text-start">
          
          <li class="nav-item ms-auto"> <!-- ms-auto empujará el elemento completamente a la derecha -->
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" id="searchInput" placeholder="Buscar" aria-label="Search">
              <ul id="resultList"></ul>
          </form>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'tienda:tienda' %}">Tienda</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'musica:musica' %}">Canciones</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'eventos:eventos' %}">Eventos</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'booking:booking' %}">Bookings</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <img src="{% static 'assets/img/icons/user.svg' %}" alt="userlogo" height="20px" width="20px">
            </a>
            <ul class="dropdown-menu dropdown-menu-end">
              {% if user.is_authenticated %}
                <!-- Muestra si el usuario está autenticado -->
                <li><a class="dropdown-item" href="{% url 'carrito:carrito' %}">Carrito</a></li>
                <li><a class="dropdown-item" href="{% url 'usuarios:ajustes' %}">Ajustes</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="{% url 'usuarios:logout' %}">Cerrar Sesión</a></li>
              {% else %}
                <!-- Muestra si el usuario no está autenticado -->
                <li><a class="dropdown-item" href="{% url 'usuarios:login' %}">Iniciar Sesión</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="{% url 'usuarios:signup' %}">Registrarse</a></li>
              {% endif %}
            </ul>
          </li>
        </ul>

      </div>
    </div>
  </div>
</nav>

LaKultural/templates/reproductor_musica.html
{% load static %}


<div class="fixed-bottom bg-dark">
    <div class="row align-items-center">
        <div class="col-lg-6">
            <div class="row align-items-center">
                <div class="col-md-3">
                    <img id="songImage" src="" alt="Imagen del álbum" style="width:100px; height:100px;">
                </div>
                <div class="col-md-6">
                    <div id="songTitle">Título de la canción</div>
                    <div id="songArtist">Nombre del artista</div>
                </div>
                <div class="col-md-3">
                    <div class="row align-items-center">
                        afegir o treure
                    </div>
                </div>          
            </div>

        </div>
        
        <div class="col-lg-6">
            <div class="row align-items-center">
                <div class="col-md-1">
                    <img src="{% static 'assets/img/icons/next_l.svg' %}" src="" alt="play_left" style="width:30px; height:30px;">
                </div>
                <div class="col-md-1">
                    <img src="{% static 'assets/img/icons/play.svg' %}" src="" alt="play_pause" style="width:30px; height:30px;">
                </div>
                <div class="col-md-1">
                    <img src="{% static 'assets/img/icons/next_r.svg' %}" src="" alt="play_right" style="width:30px; height:30px;">
                </div>
            </div>
            <div class="row align-items-center">
                barra musica
            </div>
            
        </div>

    </div>
</div>

LaKultural/templates/team.html
{% load static %}
<!-- Team-->
<section class="page-section bg-light" id="team">
    <div class="container">
        <div class="text-center">
            <h2 class="section-heading text-uppercase">Our Amazing Team</h2>
            <h3 class="section-subheading text-muted">Lorem ipsum dolor sit amet consectetur.</h3>
        </div>
        <div class="row">
            <div class="col-lg-4">
                <div class="team-member">
                    <img class="mx-auto rounded-circle" src="{% static 'assets/img/team/1.jpg' %}" alt="..." />
                    <h4>Parveen Anand</h4>
                    <p class="text-muted">Lead Designer</p>
                    <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Parveen Anand Twitter Profile"><i class="fab fa-twitter"></i></a>
                    <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Parveen Anand Facebook Profile"><i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Parveen Anand LinkedIn Profile"><i class="fab fa-linkedin-in"></i></a>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="team-member">
                    <img class="mx-auto rounded-circle" src="{% static 'assets/img/team/2.jpg" alt="..." />
                    <h4>Diana Petersen</h4>
                    <p class="text-muted">Lead Marketer</p>
                    <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Diana Petersen Twitter Profile"><i class="fab fa-twitter"></i></a>
                    <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Diana Petersen Facebook Profile"><i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Diana Petersen LinkedIn Profile"><i class="fab fa-linkedin-in"></i></a>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="team-member">
                    <img class="mx-auto rounded-circle" src="{% static 'assets/img/team/3.jpg" alt="..." />
                    <h4>Larry Parker</h4>
                    <p class="text-muted">Lead Developer</p>
                    <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Larry Parker Twitter Profile"><i class="fab fa-twitter"></i></a>
                    <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Larry Parker Facebook Profile"><i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Larry Parker LinkedIn Profile"><i class="fab fa-linkedin-in"></i></a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-8 mx-auto text-center"><p class="large text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut eaque, laboriosam veritatis, quos non quis ad perspiciatis, totam corporis ea, alias ut unde.</p></div>
        </div>
    </div>
</section>