LaKultural/LaKultural/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('usuarios/', include ('usuarios.urls')),
    path('tienda/', include ('tienda.urls')),
    path('servicios/', include ('servicios.urls')),
    path('musica/', include ('musica.urls')),
    path('eventos/', include ('eventos.urls')),
    path('booking/', include ('booking.urls')),
    path('biografia/', include ('biografia.urls')),
    path('carrito/', include ('carrito.urls')),
    path('', include ('core.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LaKultural/carrito/urls.py
from django.urls import path
from . import views

app_name = 'carrito' 

urlpatterns = [
    path('', views.carrito, name='carrito'),
    path('agregar/<int:producto_id>/', views.agregar_producto, name='agregar_producto'),
    path('quitar/<int:item_id>/', views.quitar_producto, name='quitar_producto'),    
    path('checkout/', views.checkout, name='checkout'),    
    path('update/<int:item_id>/<int:product_id>/<int:quantity>/', views.update_item_quantity, name='update_item_quantity'),
]

LaKultural/core/urls.py
from django.urls import path
from . import views

app_name = 'core' 

urlpatterns = [
    path('', views.home, name='home'),
    path('buscar/', views.buscar, name='buscar'),
]

LaKultural/tienda/urls.py
from django.urls import path
from . import views

app_name = 'tienda' 

urlpatterns = [
    path('', views.tienda, name='tienda'),
    path('tienda/<int:producto_id>', views.producto, name='producto'),
]

LaKultural/tienda/models.py
from django.db import models
from usuarios.models import Usuario

class CategoriaArticulo(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField(blank=True)

    def __str__(self):
        return self.nombre

class Producto(models.Model):
    categoria = models.ForeignKey(CategoriaArticulo, related_name='productos', on_delete=models.CASCADE)
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()
    imagen = models.ImageField(upload_to='productos/')
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    descuento = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    descuento_activo = models.BooleanField(default=False)
    stock = models.IntegerField(default=0)  # Añadido para control de inventario
    activo = models.BooleanField(default=True)  # Para activar/desactivar productos fácilmente
    modelo = models.CharField(max_length=100, blank=True, null=True) # Opcional para productos no ropa
    tallas = models.CharField(max_length=255, blank=True, null=True)  

    def __str__(self):
        return self.nombre

class ImagenProducto(models.Model):
    producto = models.ForeignKey(Producto, related_name='imagenes', on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to='imagenes_productos/')

    def __str__(self):
        return f"Imagen de {self.producto.nombre}"

LaKultural/tienda/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from .models import Producto

def tienda(request):
    productos = Producto.objects.all()
    contexto = {'productos':productos}
    return render(request, 'tienda/tienda.html', contexto)


def producto(request, producto_id):
    producto = get_object_or_404(Producto, pk=producto_id)
    #Filtrar productos con la misma CategoriaArticulo
    related_productos = Producto.objects.filter(categoria=producto.categoria).exclude(pk=producto_id)

    contexto = {'producto':producto, 
                'related_productos':related_productos}

    return render(request, 'tienda/producto.html', contexto)

LaKultural/tienda/templates/tienda/faqs.html
{% load static %}
<h2 class="mb-4">FAQS</h2>
<div class="accordion" id="FAQaccordion">

    <div class="accordion-item">
      <h2 class="accordion-header">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
            ¿Cómo realizo una compra en tu tienda?
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse" data-bs-parent="#FAQaccordion">
        <div class="accordion-body">
          <strong></strong> Puedes realizar una compra navegando por nuestra selección de productos y añadiendo los artículos deseados al carrito de compras. Luego, procede al pago utilizando PayPal, nuestro método de pago seguro.
        </div>
      </div>
    </div>

    <div class="accordion-item">
      <h2 class="accordion-header">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
            ¿Cuál es el plazo y coste de entrega de mi pedido?
        </button>
      </h2>
      <div id="collapseTwo" class="accordion-collapse collapse" data-bs-parent="#FAQaccordion">
        <div class="accordion-body">
            El plazo de entrega varía según tu ubicación y la disponibilidad del producto. Por lo general, los pedidos se envían en un plazo de 2 días hábiles. Una vez enviado, recibirás un correo electrónico de confirmación con información de seguimiento.
            El costo de envío se calculará automáticamente durante el proceso de compra, basado en tu ubicación y el peso de los productos en tu pedido.

        </div>
      </div>
    </div>

    <div class="accordion-item">
      <h2 class="accordion-header">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
            ¿Qué debo hacer si mi pedido llega con defectos o dañado?
        </button>
      </h2>
      <div id="collapseThree" class="accordion-collapse collapse" data-bs-parent="#FAQaccordion">
        <div class="accordion-body">
            Lamentamos cualquier inconveniente causado por productos defectuosos o dañados. Por favor, ponte en contacto con nuestro equipo de atención al cliente dentro de los 15 días posteriores a la recepción del pedido para organizar una devolución y reemplazo.
        </div>
      </div>
    </div>

    <div class="accordion-item">
        <h2 class="accordion-header">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
            ¿Aceptan devoluciones?
          </button>
        </h2>
        <div id="collapseThree" class="accordion-collapse collapse" data-bs-parent="#FAQaccordion">
          <div class="accordion-body">
            Sí, aceptamos devoluciones dentro de los [X] días posteriores a la recepción del pedido. Los productos deben estar en su estado original, sin usar y con las etiquetas intactas. Por favor, ponte en contacto con nuestro equipo de atención al cliente para iniciar el proceso de devolución.

          </div>
        </div>
      </div>


      <div class="accordion-item">
        <h2 class="accordion-header">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
            ¿Puedo cancelar o modificar mi pedido después de realizarlo?          </button>
        </h2>
        <div id="collapseThree" class="accordion-collapse collapse" data-bs-parent="#FAQaccordion">
          <div class="accordion-body">
            Si deseas cancelar o modificar tu pedido, por favor, ponte en contacto con nuestro equipo de atención al cliente lo antes posible. Haremos nuestro mejor esfuerzo para satisfacer tu solicitud, siempre que sea posible.
          </div>
        </div>
      </div>
  </div>

LaKultural/tienda/templates/tienda/producto.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Masthead-->
<header class="masthead">
    <div class="text-center">
        <h1 class="section-heading text-uppercase">TIENDA</h1>
    </div>
</header>

<div class="container text-start">
  <div class="row mb-5">
    <div class="col-lg-6 col-product">
      <div class="event-card m-3 p-3 event-card-producto">
        {% if producto.imagen %}
        <img src="{{ producto.imagen.url }}" alt="{{ producto.nombre }}" class="img-fluid card-img-top rounded-3">
        {% else %}
        <p>No hay imagen disponible.</p>
        {% endif %}
      </div>
      
      <div class="d-flex flex-column justify-content-center">
        <h2>{{producto.nombre}}</h2>
        <p>{{producto.descripcion}}</p>
        <p>{{producto.precio}} €</p>
      </div>

    </div>

    <div class="col-lg-6 tarjeta-info-producto col-product">
      <!-- Descripción -->
      <div class="row">
          <div class="col">
            <h3 class="mb-3">DESCRIPCIÓN</h3>
            <p>{{ producto.descripcion }}</p>
          </div>
      </div>
  
      <!-- Información Adicional -->
      <div class="row mt-4">
        <div class="col">
          <a href="{% url 'carrito:agregar_producto' producto_id=producto.id %}" class="btn btn-light btn-compra text-uppercase mb-5 w-100">Añadir al carrito</a>
          <h3>INFORMACIÓN ADICIONAL</h3>
          <!-- Selección de modelo y talla. Deberá aparecer una lista con cada talla y otra con cada modelo y poder seleccionar la combinacion adecuada. Incluir un boton para abrir una pagina donde hay infomracion para seleccion talla adecuada -->
          <label for="talla">Selecciona tu talla:</label>
          <select name="talla" id="talla" class='label-product'>
            <option value="s">S</option>
            <option value="m">M</option>
            <option value="l">L</option>
            <option value="xl">XL</option>
          </select>
          <label for="talla">Selecciona tu modelo:</label>
          <select name="modelo" id="modelo" class='label-product'>
            <option value="modelo1">Modelo 1</option>
            <option value="modelo2">Modelo 2</option>
            <option value="modelo3">Modelo 3</option>
            <option value="modelo4">Modelo 4</option>
          </select>
          <button id="abrirModal" class="btn btn-dark text-uppercase">Guía de tallas</button>
        </div>
      </div>

      <!-- Política de devoluciones -->
      <div class="row mt-4">
        <div class="col">
          <p>No se pueden realizar cambios ni devoluciones de entradas ya adquiridas. Únicamente se reembolsará el importe de las entradas en caso de incidencia técnica o de cancelación del evento por parte de la organización. Las cancelaciones no incluyen casos de fuerza mayor.</p>
        </div>
      </div>
    </div>
  </div>

  <div class="row mb-5">
    <!-- Inclueix events relacions i FAQS-->
    {% include 'tienda/related_products.html' %}
    {% include 'tienda/faqs.html' %}

  </div>

</div>
<!-- Modal -->
<div id="modalTallas" class="modal" style="display: none;">
  <div class="modal-content">
    <span class="close">&times;</span>
    <p>Aquí va tu guía de tallas...</p>
  </div>
</div>

{% endblock %}

LaKultural/tienda/templates/tienda/related_products.html
{% load static %}

<h2 class="mb-4">Otros artículos de interés</h2>
<div class="row flex-nowrap overflow-auto row-scrollable mb-5">
  {% for producto in related_productos %}
  <a href="{% url 'tienda:producto' producto.id %}">
  <div class="col-6 col-md-3 col-lg-2">
    <div class="card card-background card-shadow bg-dark text-white h-100 border-0"> <!-- Añadir un margen horizontal para espacio entre tarjetas -->
      <img class="card-img-top" src="{{ producto.imagen.url }}" alt="{{ producto.nombre }}">
      <div class="card-body d-flex flex-column">
        <h5 class="card-title">{{ producto.nombre }}</h5>
        <p class="card-text"><small>{{ producto.descripcion }}</small></p>
        <p class="card-text"><small>{{ producto.precio }}</small></p>
        <div class="mt-auto">
          <!-- Botones o enlaces aquí -->
        </div>
      </div>
    </div>
  </div>
  </a>
  {% endfor %}
</div>

LaKultural/tienda/templates/tienda/tienda.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Masthead-->
<header class="masthead">
    <div class="text-center">
        <h1 class="section-heading text-uppercase">TIENDA</h1>
    </div>
</header>

<div class="container py-4 text-start">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 g-4">
        <!-- Event Card -->
        {% for producto in productos %}
        <div class="col">
            <a href="{% url 'tienda:producto' producto.id %}">
            <div class="card card-background card-movement bg-dark text-white h-100 border-0">
                {% if producto.imagen %}
                <img src="{{ producto.imagen.url }}" alt="{{ producto.nombre }}" class="img-fluid card-img-top rounded-3">
                {% else %}
                <p>No hay imagen disponible.</p>
                {% endif %}
                <div class="card-body">
                    <h5 class="card-title">{{ producto.nombre}}</h5>
                    <p class="card-text">{{ producto.categoria}}</p>
                </div>
                <div class="card-footer">
                    <p>{{ producto.precio}}€</p>
                </div>
            </div>
            </a>
        </div>
        {% endfor%}
    </div>
</div>

{% endblock %}